#!/bin/bash

# Parameters
PROVIDER_NAME=federico
PROVIDER_HOST=192.168.0.13
SENSOR_NAME=pi
SENSOR_HOST=192.168.0.18
CLIENT_NAME=federico
CLIENT_HOST=localhost

PROVIDER=$PROVIDER_NAME@$PROVIDER_HOST
SENSOR=$SENSOR_NAME@$SENSOR_HOST
CLIENT=$CLIENT_NAME@$CLIENT_HOST